import Head from "next/head";
import Image from "next/image";
import { Button } from "react-bootstrap";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} bg-warning`}>
        <section className={`${styles.hero} `}>
          <div className="container vh-100">
            <div className="row ">
              <div className="col-xs-12 col-lg-6 ">
                <h1>lorem ipsum </h1>
                <p>
                  Officia Lorem duis ut eu tempor minim adipisicing aliquip
                  minim minim ad ut culpa pariatur.
                </p>
                <Button variant="outline-light">
                  <a href="#">Learn More</a>
                </Button>
              </div>

              <div className="col-6">
                <h1 className="text-right">lorem ipsum </h1>
              </div>
            </div>
          </div>
        </section>

       
      </main>
    </div>
  );
}
